# Generated by Django 3.2.7 on 2022-11-22 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 9, 47, 52, 766133), null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 22, 9, 47, 52, 766133), null=True),
        ),
    ]
