# Generated by Django 4.1.5 on 2023-02-16 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 16, 13, 3, 13, 5197), null=True),
        ),
    ]
