# Generated by Django 3.2.7 on 2022-11-22 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0002_auto_20221122_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 10, 18, 24, 290692), null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 22, 10, 18, 24, 290692), null=True),
        ),
    ]
