# Generated by Django 4.1.5 on 2023-02-16 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0004_examinstructions_interview_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview_language',
            old_name='interview_id',
            new_name='interview_language_id',
        ),
        migrations.RenameField(
            model_name='language_settings',
            old_name='interview_id',
            new_name='interview_language_id',
        ),
        migrations.AlterField(
            model_name='language_settings',
            name='advanced_level_hours',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 16, 14, 16, 11, 424397), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='language_settings',
            name='beginner_level_hours',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 16, 14, 16, 11, 424397), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='language_settings',
            name='intermediate_level_hours',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 16, 14, 16, 11, 424397), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 16, 14, 16, 11, 422376), null=True),
        ),
    ]
