# Generated by Django 3.2.7 on 2022-12-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0007_auto_20221221_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_advanced',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 19, 53, 567696), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_beginner',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 19, 53, 567696), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_intermediate',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 19, 53, 567696), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 19, 53, 567696), null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 19, 53, 567696), null=True),
        ),
    ]
