# Generated by Django 4.1.5 on 2023-02-13 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement_site', '0008_auto_20221221_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInstructions',
            fields=[
                ('instruction_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('instruction', models.CharField(blank=True, max_length=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Exam Instructions',
                'verbose_name_plural': 'Exam Instructions',
            },
        ),
        migrations.AlterModelOptions(
            name='exam_details',
            options={'verbose_name': 'Exam Details', 'verbose_name_plural': 'Exams Details'},
        ),
        migrations.AlterModelOptions(
            name='student_profile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profile'},
        ),
        migrations.AlterModelOptions(
            name='subject_details',
            options={'verbose_name': 'Subject Details', 'verbose_name_plural': 'Subject Details'},
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_advanced',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 13, 9, 33, 56, 263072), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_beginner',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 13, 9, 33, 56, 263072), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='exam_hours_intermediate',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 2, 13, 9, 33, 56, 263072), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 13, 9, 33, 56, 260088), null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 9, 33, 56, 260088), null=True),
        ),
    ]
